### ISSUE TITLE
libs folder is missing

### ISSUE THREAD

**Issue by meryusha** [epic-kitchens/C2-Action-Detection#2]
Hello, 
First, thank you for providing this repo
I was following the instructions to work with the BMN code but didn't find the **_libs_** folder where the training script is supposed to be.
Could you please help me with that?

**Comment by antoninofurnari** [comment]
Hello,

Thank you for opening this issue. There was an error in the `train_ek100.sh` script and in the README. In practice, the training script is not in the `libs` directory, but it is placed directly in `BMNProposalGenerator`. I corrected the script and README. Can you try now and see if this solves the issue?

Best,
Antonino
