### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by BAOSHAN0123** [epic-kitchens/C2-Action-Detection#6]
I compute the validation detections using the following command:

python run_net.py --cfg ../epic-kitchens-slowfast-master/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml \
  NUM_GPUS 1 \
  OUTPUT_DIR .. \
  EPICKITCHENS.VISUAL_DATA_DIR ../epic-kitchens-slowfast-master/dataset \
  EPICKITCHENS.ANNOTATIONS_DIR ../epic-kitchens-100-annotations-master \
  TRAIN.ENABLE False \
  TEST.ENABLE True \
  TEST.CHECKPOINT_FILE_PATH ../epic-kitchens-slowfast-master/SlowFast.pyth \
  EPICKITCHENS.TEST_LIST ../BMN/output/ek100/result_proposal-test.pkl \
  EPICKITCHENS.TEST_SPLIT test \
  TEST.BATCH_SIZE 1

However, I account with KeyError. Cound you please give any advice?

[INFO: epickitchens.py:   47]: Constructing EPIC-KITCHENS test...
[INFO: epickitchens.py:   81]: Constructing epickitchens dataloader (size: 1454740) from ['../epic-kitchens-100-annotations-master/../BMN/output/ek100/result_proposal-test.pkl']
[INFO: run_net.py:  213]: Testing model for 1454740 iterations
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
../epic-kitchens-slowfast-master/dataset/P07/rgb_frames/P07_104
Traceback (most recent call last):
  File "/disk/lbs/c2ad/SlowFast/run_net.py", line 399, in <module>
    main()
  File "/disk/lbs/c2ad/SlowFast/run_net.py", line 394, in main
    test(cfg=cfg)
  File "/disk/lbs/c2ad/SlowFast/run_net.py", line 243, in test
    preds, labels, metadata = perform_test(test_loader, model, test_meter, cfg)
  File "/disk/lbs/c2ad/SlowFast/run_net.py", line 116, in perform_test
    metadata['narration_id'].extend(meta[i]['narration_id'])
KeyError: 0

**Comment by antoninofurnari** [comment]
Hello,

Are you running this (https://github.com/epic-kitchens/C2-Action-Detection/blob/master/SlowFastProposalClassifier/run_net.py) `run_net.py` or the one provided with the SlowFast repo? You should use the `run_net.py` file provided with this repo as per instructions.

From your error message it looks like you are using the one provided in the epic-kitchens-slowfast repo instead. Indeed, there is no `metadata['narration_id'].extend(meta[i]['narration_id'])` at line 116 of https://github.com/epic-kitchens/C2-Action-Detection/blob/master/SlowFastProposalClassifier/run_net.py#L116

Can you please try running the `run_net.py` provided in this repo and let me know if this solves the issue?

Thanks,
Antonino

**Comment by BAOSHAN0123** [comment]
Hi,
I do use the `run_net.py` provided in this repo [https://github.com/epic-kitchens/C2-Action-Detection/blob/master/SlowFastProposalClassifier/run_net.py](url) and run it, and the above error occurred. Could you give some unique opinions?

**Comment by antoninofurnari** [comment]
Did you move or modify the file? 

It is not clear to me why your error is pointing to file "/disk/lbs/c2ad/SlowFast/run_net.py" rather than something like "/disk/lbs/c2ad/SlowFastProposalClassifier/run_net.py" and it is not clear to me why it is giving these errors:

- File "/disk/lbs/c2ad/SlowFast/run_net.py", line 399, in main()
while main() should be located at line 387: https://github.com/epic-kitchens/C2-Action-Detection/blob/master/SlowFastProposalClassifier/run_net.py#L387

- File "/disk/lbs/c2ad/SlowFast/run_net.py", line 394, in main test(cfg=cfg)
while test(cfg=cfg) is located at line 382: File "/disk/lbs/c2ad/SlowFast/run_net.py", line 394, in main
test(cfg=cfg)

- File "/disk/lbs/c2ad/SlowFast/run_net.py", line 116, in perform_test metadata['narration_id'].extend(meta[i]['narration_id'])
while metadata['narration_id'].extend(meta[i]['narration_id']) is located at line 109: https://github.com/epic-kitchens/C2-Action-Detection/blob/master/SlowFastProposalClassifier/run_net.py#L109

It looks like some things changed in the original code, and it is difficult to help this way. Can you make a brand new clone of the repository and try again?

**Comment by BAOSHAN0123** [comment]
Hello,
In order to prevent my own modifications from causing problems in the program, I re-cloned a master project as you suggested, but there was still an unknown error message:

Execution instruction
```
python run_net.py --cfg /disk/lbs/epic-kitchens-slowfast-master/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml \
 NUM_GPUS 1 \
 OUTPUT_DIR .. \
 EPICKITCHENS.VISUAL_DATA_DIR /disk/lbs/dataset \
 EPICKITCHENS.ANNOTATIONS_DIR /disk/lbs/epic-kitchens-100-annotations-master \
 TRAIN.ENABLE False \
 TEST.ENABLE True \
 TEST.CHECKPOINT_FILE_PATH /disk/lbs/SlowFast.pyth \
 EPICKITCHENS.TEST_LIST /disk/lbs/C2-Action-Detection-master/BMNProposalGenerator/output/ek100/result_proposal-validation.pkl \
 EPICKITCHENS.TEST_SPLIT validation \
 TEST.BATCH_SIZE 1
```

Error information:
```
[INFO: run_net.py:  204]: Testing model for 1583850 iterations
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Traceback (most recent call last):
Reading failed. Will retry.
  File "run_net.py", line 389, in <module>
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
    main()
  File "run_net.py", line 384, in main
    test(cfg=cfg)
  File "run_net.py", line 234, in test
    preds, labels, metadata = perform_test(test_loader, model, test_meter, cfg)
  File "run_net.py", line 51, in perform_test
    for cur_iter, (inputs, labels, video_idx, meta) in enumerate(test_loader):
  File "/disk/lbs/app/anaconda/envs/c2ad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/disk/lbs/app/anaconda/envs/c2ad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/disk/lbs/app/anaconda/envs/c2ad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
Reading failed. Will retry.
    data.reraise()
  File "/disk/lbs/app/anaconda/envs/c2ad/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
Exception: Caught Exception in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/disk/lbs/app/anaconda/envs/c2ad/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/disk/lbs/app/anaconda/envs/c2ad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk/lbs/app/anaconda/envs/c2ad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk/lbs/epic-kitchens-slowfast-master/slowfast/datasets/epickitchens.py", line 129, in __getitem__
    frames = pack_frames_to_video_clip(self.cfg, self._video_records[index], temporal_sample_index)
  File "/disk/lbs/epic-kitchens-slowfast-master/slowfast/datasets/frame_loader.py", line 44, in pack_frames_to_video_clip
    frames = utils.retry_load_images(img_paths)
  File "/disk/lbs/epic-kitchens-slowfast-master/slowfast/datasets/utils.py", line 36, in retry_load_images
    raise Exception("Failed to load images {}".format(image_paths))
Exception: Failed to load images ['/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001405.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001407.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001409.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001411.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001413.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001415.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001417.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001419.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001421.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001423.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001425.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001427.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001429.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001431.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001433.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001435.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001437.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001439.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001441.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001443.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001445.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001447.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001449.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001451.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001453.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001455.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001457.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001459.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001461.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001463.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001465.jpg', '/disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001468.jpg']
```

This appears to be an error caused by frame content failing to load, I don't know why this is the case, the data frame is also the corresponding EPIC-100 RGB-FRAME, like this:
```
├── dataset
|   ├── P01
|   |   ├── rgb_frames
|   |   |   |    ├── P01_01
|   |   |   |    |    ├── frame_0000000000.jpg
|   |   |   |    |    ├── frame_0000000001.jpg
|   |   |   |    |    ├── .
|   |   |   |    |    ├── .
|   |   |   |    |    ├── .
|   |   |   |    .    
|   |   |   |    .    
|   |   |   |    .
|   ├── .
|   ├── .
|   ├── .
|   ├── P37
|   |   ├── rgb_frames
|   |   |   |    ├── P37_101
|   |   |   |    |    ├── frame_0000000000.jpg
|   |   |   |    |    ├── frame_0000000001.jpg
|   |   |   |    |    ├── .
|   |   |   |    |    ├── .
|   |   |   |    |    ├── .
|   |   |   |    .    
|   |   |   |    .    
|   |   |   |    .

```
Everything is ok, but the mistakes continued, this question puzzled me for a long time. I would appreciate it if you could give me some advice.

Thanks,
A beginner just getting started

**Comment by antoninofurnari** [comment]
Hello,

Thanks for re-cloning and trying again! As you noted, the problem is probably due to the progam not being able to read the jpg files. In particular, the error happens here:

https://github.com/epic-kitchens/epic-kitchens-slowfast/blob/master/slowfast/datasets/utils.py#L13

If you look at the code:

```python
 for i in range(retry):
        imgs = [cv2.imread(image_path) for image_path in image_paths]

        if all(img is not None for img in imgs):
            if backend == "pytorch":
                imgs = torch.as_tensor(np.stack(imgs))
            return imgs
        else:
            logger.warn("Reading failed. Will retry.")
            time.sleep(1.0)
        if i == retry - 1:
            raise Exception("Failed to load images {}".format(image_paths))
```

the function will try to read the images for a given number of times. The images are loaded with `cv2.imread`, which will return `None` if the image cannot be loaded/decoded. If even just one of the images cannot be loaded, all retries, the exception is raised. 

I think a good starting point to understand what's happening is to check if all images in the list provided in the arror do actually exist. One way to do it is to ls each image, e.g.:

`ls /disk/lbs/dataset/P11/rgb_frames/P11_21/frame_0000001405.jpg`

Since it's many images, a good idea would be to start by checking a few images at the beginning of the list and a few ones at the end. It migh happen that some filenames are not generated correctly, in which case the files would not exist. If all files exist, please try to open some of them using an image viewer to check that these images can actually be decoded.

Since this seems to be more an issue of data loading with SlowFast, it would also be a good idea to follow the instructions at https://github.com/epic-kitchens/epic-kitchens-slowfast and check that you can actually test the pretrained model on the validation set.

Hope this helps.

Antonino
