### ISSUE TITLE
Error while reproducing the results.

### ISSUE THREAD

**Issue by kajal-puri** [epic-kitchens/C2-Action-Detection#7]
Hi, I'm trying to reproduce the results of Action Detection experiment for EPIC-KITCHEN 100 dataset. First of all, thank you for releasing the code. I follow the instructions step by step given in the ReadME file. I get the following error on the last step - "Computing Validation/Test Detections". I write the following command :

python run_net.py --cfg ../epic-kitchens-slowfast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 
OUTPUT_DIR ../results/ 
EPICKITCHENS.VISUAL_DATA_DIR ../EPIC-KITCHENS/ 
EPICKITCHENS.ANNOTATIONS_DIR ../anno/ 
TRAIN.ENABLE False 
TEST.ENABLE True 
TEST.CHECKPOINT_FILE_PATH ../SlowFast.pyth 
EPICKITCHENS.TEST_LIST ../C2-Action-Detection/BMNProposalGenerator/output/ek100/result_proposal-test.pkl
EPICKITCHENS.TEST_SPLIT test
TEST.BATCH_SIZE 2

The program start running and prints out the model and other variables correctly. And then after 2-3 minutes give the following error : 

from ['/home/user/puri/va/C2-Action-Detection/BMNProposalGenerator/output/ek100/result_proposal-test.pkl']
[INFO: run_net.py:  202]: Testing model for 727370 iterations
Traceback (most recent call last):
  File "run_net.py", line 387, in <module>
    main()
  File "run_net.py", line 382, in main
    test(cfg=cfg)
  File "run_net.py", line 232, in test
    preds, labels, metadata = perform_test(test_loader, model, test_meter, cfg)
  File "run_net.py", line 49, in perform_test
    for cur_iter, (inputs, labels, video_idx, meta) in enumerate(test_loader):
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'stop_timestamp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/puri/va/C2-Action-Detection/SlowFastProposalClassifier/slowfast/datasets/epickitchens.py", line 129, in __getitem__
    frames = pack_frames_to_video_clip(self.cfg, self._video_records[index], temporal_sample_index)
  File "/home/user/puri/va/C2-Action-Detection/SlowFastProposalClassifier/slowfast/datasets/frame_loader.py", line 34, in pack_frames_to_video_clip
    video_record.num_frames,
  File "/home/user/puri/va/C2-Action-Detection/SlowFastProposalClassifier/slowfast/datasets/epickitchens_record.py", line 43, in num_frames
    return self.end_frame - self.start_frame
  File "/home/user/puri/va/C2-Action-Detection/SlowFastProposalClassifier/slowfast/datasets/epickitchens_record.py", line 34, in end_frame
    return int(round(timestamp_to_sec(self._series['stop_timestamp']) * self.fps))
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/pandas/core/series.py", line 991, in _get_value
    loc = self.index.get_loc(label)
  File "/home/user/puri/miniconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2893, in get_loc
    raise KeyError(key) from err
KeyError: 'stop_timestamp'

I don't really understand what this error is trying to tell as it just prints out a simple error message KeyError: 'stop_timestamp' . Can you tell what this error is trying to point so I can try fixing it? Thank you so much!

**Comment by antoninofurnari** [comment]
Hello,

The line returning the error is this one:

https://github.com/epic-kitchens/epic-kitchens-slowfast/blob/master/slowfast/datasets/epickitchens_record.py#L34

```python
return int(round(timestamp_to_sec(self._series['stop_timestamp']) * self.fps))
```

Apparently, you get the error when trying to access `self._series['stop_timestamp']`, where `_series` has been loaded from the specified pickle file (see https://github.com/epic-kitchens/epic-kitchens-slowfast/blob/158156a74bd088eee6fe15cfc1d2f41fc85d1509/slowfast/datasets/epickitchens.py#L70). 

Can you try to load the pickle file you specified ('/home/user/puri/va/C2-Action-Detection/BMNProposalGenerator/output/ek100/result_proposal-test.pkl') and see if it actually contains the `stop_timestamp` column? You could do it as follows:

```python
import pandas as pd
data = pd.read_pickle('/home/user/puri/va/C2-Action-Detection/BMNProposalGenerator/output/ek100/result_proposal-test.pkl')
print(data.head())
```

You should see something like this:

```
participant_id video_id  start_seconds  stop_seconds start_timestamp stop_timestamp  start_frame  stop_frame     score
narration_id
P07_104_0               P07  P07_104      80.967167     81.452000      0:01:20.96     0:01:21.45         4049        4073  0.641398
P07_104_1               P07  P07_104      80.724750     81.209583      0:01:20.72     0:01:21.20         4037        4061  0.581054
P07_104_2               P07  P07_104      80.967167     81.209583      0:01:20.96     0:01:21.20         4049        4061  0.523063
P07_104_3               P07  P07_104      81.209583     81.694417      0:01:21.20     0:01:21.69         4061        4085  0.517933
P07_104_4               P07  P07_104      81.209583     81.452000      0:01:21.20     0:01:21.45         4061        4073  0.466026
```

Best,
Antonino

**Comment by kajal-puri** [comment]
Hi Antonio, 

Thanks for the reply. I just did, as u specified and it gave me the following output which doesn't contain the start_timestamp and stop_timestamp section. So I believe I've downloaded the wrong pkl file? Can you point me out the correct one? I believe I've followed the link in the github ReadMe. 

participant_id video_id  start_seconds  stop_seconds 
narration_id                                                        
P07_104_0               P07  P07_104      80.967167     81.452000   
P07_104_1               P07  P07_104      80.724750     81.209583   
P07_104_2               P07  P07_104      80.967167     81.209583   
P07_104_3               P07  P07_104      81.209583     81.694417   
P07_104_4               P07  P07_104      81.209583     81.452000   

                           start_frame  stop_frame     score  
narration_id                                     
P07_104_0            4049        4073  0.641398  
P07_104_1            4037        4061  0.581054  
P07_104_2            4049        4061  0.523063  
P07_104_3            4061        4085  0.517933  
P07_104_4            4061        4073  0.466026

**Comment by antoninofurnari** [comment]
You should try with the pickle included in this repo:

https://github.com/epic-kitchens/C2-Action-Detection/blob/master/BMNProposalGenerator/output/ek100/result_proposal-test.pkl

Otherwise, you should be able to generate it yourself by following the instructions at https://github.com/epic-kitchens/C2-Action-Detection/#action-proposals-generator

Hope this solves the issue.

Best,
Antonino

**Comment by kajal-puri** [comment]
https://github.com/epic-kitchens/C2-Action-Detection/blob/master/BMNProposalGenerator/output/ek100/result_proposal-test.pkl

I have just downloaded the pkl file again (tried on both test and validation) from the above mentioned link and it doesn't include the start_timestamp and stop_timestamp section. Can you download it yourself and check again from this link? I'm trying to generate them myself using the other step that you've mentioned and will let you know if it works!

Thank you for the reply.

**Comment by antoninofurnari** [comment]
I just realized that the `pkl` files on the repo where in an outdated format which did not contain the `start_timestamp` and `stop_timestamp` columns. I now uploaded the updated files. This should be solved in https://github.com/epic-kitchens/C2-Action-Detection/commit/fafd68dc60c751a5da38a9ae215e181c5a3ab0ed. 

Can you try with the updated files?

Thanks,
Antonino

**Comment by kajal-puri** [comment]
Thanks for updating the pkl files. They work fine now, I just checked. 

After updating these, I'm getting the following error. Do you have any idea why this error could be happening?

[INFO: epickitchens.py:   43]: Constructing EPIC-KITCHENS test...
[INFO: epickitchens.py:   77]: Constructing epickitchens dataloader (size: 1454740) from ['/home/user/puri/va/C2-Action-Detection/BMNProposalGenerator/output/ek100/result_proposal-test.pkl']
[INFO: run_net.py:  202]: Testing model for 1454740 iterations
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Traceback (most recent call last):
  File "run_net.py", line 387, in <module>
    main()
  File "run_net.py", line 382, in main
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
Reading failed. Will retry.
    test(cfg=cfg)
  File "run_net.py", line 232, in test
Reading failed. Will retry.
    preds, labels, metadata = perform_test(test_loader, model, test_meter, cfg)
  File "run_net.py", line 49, in perform_test
    for cur_iter, (inputs, labels, video_idx, meta) in enumerate(test_loader):
  File "/home/user/puri/miniconda3/envs/c2-action-detection-bmn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/user/puri/miniconda3/envs/c2-action-detection-bmn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/user/puri/miniconda3/envs/c2-action-detection-bmn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/user/puri/miniconda3/envs/c2-action-detection-bmn/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
Exception: Caught Exception in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/puri/miniconda3/envs/c2-action-detection-bmn/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/puri/miniconda3/envs/c2-action-detection-bmn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/puri/miniconda3/envs/c2-action-detection-bmn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/puri/va/C2-Action-Detection/SlowFastProposalClassifier/slowfast/datasets/epickitchens.py", line 129, in __getitem__
    frames = pack_frames_to_video_clip(self.cfg, self._video_records[index], temporal_sample_index)
  File "/home/user/puri/va/C2-Action-Detection/SlowFastProposalClassifier/slowfast/datasets/frame_loader.py", line 44, in pack_frames_to_video_clip
    frames = utils.retry_load_images(img_paths)
  File "/home/user/puri/va/C2-Action-Detection/SlowFastProposalClassifier/slowfast/datasets/utils.py", line 36, in retry_load_images
    raise Exception("Failed to load images {}".format(image_paths))
Exception: Failed to load images ['/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004049.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004050.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004052.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004054.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004055.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004057.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004059.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004060.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004062.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004064.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004065.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004067.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004069.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004070.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg']

**Comment by antoninofurnari** [comment]
Hello,

That error means that there was an issue reading at least one of the frames in the list. I'd say a good starting point to debug is to check whether those images actually exist. I guess you can check it by doing `ls filename.jpg` in a bash shell for all files in the list:

```
['/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004049.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004050.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004052.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004054.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004055.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004057.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004059.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004060.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004062.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004064.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004065.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004067.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004069.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004070.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg', '/home/user/puri/EPIC-KITCHENS//P07/rgb_frames/P07_104/frame_0000004071.jpg']
```

Since this code is based on the epic-kitchens-slowfast repo, if you have not already done it, it could be a good idea to follow the instructions at https://github.com/epic-kitchens/epic-kitchens-slowfast and check if you can correctly validate the model on the validation set. If you can do that, then there must be an issue with this repo and we will try to solve it together.

Best,
Antonino

**Comment by kajal-puri** [comment]
Thanks for the reply!

I just checked and you're right these files do not exist. I am using this [link](https://github.com/epic-kitchens/epic-kitchens-download-scripts) mentioned on the SLOWFAST repo to download the datasets and as mentioned here there are two directories created by the name of **P01** and **P27** whereas the missing frames addressed are in _P07_ which doesn't exist in the dataset that I have downloaded. Do you know if the dataset name has been changed from P07 to P01 or something that I'm missing here?

**Comment by antoninofurnari** [comment]
Hello,

After following the instructions of the [epic-kitchens-download-scripts](https://github.com/epic-kitchens/epic-kitchens-download-scripts) repo you should end up with many more than two directories. Each of the directories contains frames of video of one of the subjects, so you should end up with many more folder (one per subject). 

May it be that you only launched the `python epic_downloader.py --errata` command? This will download only files for which we provided some updates a few months ago. You should download all frames with, e.g., `python epic_downloader.py --rgb-frames`. 

Can you try that and see if it solves the issue?

**Comment by kajal-puri** [comment]
Apologies for the late response. 

Is it necessary to download the whole dataset (more than 500 GB) in order to perform the testing as well? Generally, there is a "test" directory in which all the test/demo data is stored so that it is easy to reproduce a few results. As I'm using the pre-trained model, is there any such option available where I can only download the required data for testing and not the whole dataset (as I have already downloaded the dataset/video features for each video)? Let me know your thoughts. Thank you!

**Comment by antoninofurnari** [comment]
Hello,

It should not be necessary to download the whole dataset if you only intend to perform testing. You should refer to the [epic-kitchens-download-scripts](https://github.com/epic-kitchens/epic-kitchens-download-scripts) repo to see if there an option to only download test videos. In case you can't find one, you could open an issue there to receive guidance.

Hope this helps.
