### ISSUE TITLE
Error in the number of frames

### ISSUE THREAD

**Issue by VioletGreenLi** [epic-kitchens/C2-Action-Detection#8]
According to https://github.com/epic-kitchens/epic-kitchens-100-annotations/blob/master/EPIC_100_video_info.csv.
Experiment P08_19 should have a video 276.811111 seconds at fps 90, which corresponds to 276.811111*90 = 24913 frames.
But in the rgb files downloaded from https://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d/frames_rgb_flow/rgb/test/P18/P18_09.tar,
the number of frames is 16622.
Could you please specify which is correct?
Same problems also exist with the following IDs: 'P06_107', 'P06_12', 'P28_01', 'P06_110'.

**Comment by dimadamen** [comment]
All videos were unified to the same frame rate before extracting frames, so frames were *not* extracted at 90fps even though this is the original fps of the video recording. This applies to all videos of high frame rate. 
You can read the details of how all videos were re-encoded to 50 of 60fps. Videos P08_19, P06_12, P28_01 were re-extracted to 60fps as this is the fps of all videos captured in epic-kitchens-55. The other two P06_107 and P06_110 were re-encoded to 50fps which is for all videos captured in epic-kitchens-100.

**Comment by dimadamen** [comment]
The docker can be seen here: -r 50 showcases the encoding
<img width="941" alt="Screenshot 2023-05-24 at 15 03 24" src="https://github.com/epic-kitchens/C2-Action-Detection/assets/9195098/fec3e215-41f8-4cc3-a9c9-9216e572fa7b">

**Comment by VioletGreenLi** [comment]
Thanks for specifying!
